---
- name: Deploy a Builder EC2 instance
  hosts: localhost
  gather_facts: false

  vars:
    region: eu-central-1
    instance_type: t2.micro
    ami: ami-0caef02b518350c8b                      # Ubuntu 22.04
    keypair: devops-hw13-key
    name: devops_hw13_builder

  tasks:
    - name: Create an ec2 instance
      ec2:
        key_name: "{{keypair}}"
        group: EC2SecurityGroup-1
        instance_type: "{{instance_type}}"
        image: "{{ami}}"
        wait: true
        region: "{{region}}"
        count: 1
        instance_tags:
          Name: "{{name}}"
        assign_public_ip: true


- name: Test Builder
  gather_facts: false
  hosts: "tag_Name_{{name}}"
  vars:
    ansible_ssh_private_key_file: ./devops-hw13.key
    ansible_ssh_user: ubuntu
  tasks:
    - name: Run Shell Command
      command: uname -a
      register: test

    - name: Show Output of Shell Command
      debug:
        msg: "{{test}}"
