---
- name: Ansible Test Playbook
  gather_facts: false
  hosts: tag_Name_devops_hw13_builder
  vars:
    ansible_ssh_private_key_file: ./devops-hw13.key
    ansible_ssh_user: ubuntu
  tasks:
    - name: Run Shell Command
      command: echo "Hello World"
