---
- name: Create a Builder EC2 instance
  hosts: localhost
  gather_facts: false

  roles:
    - role: instance_builder

- name: Create a Webserver EC2 instance
  hosts: localhost
  gather_facts: false

  roles:
    - role: instance_webserver

- name: Test Builder
  gather_facts: false
  hosts: tag_Name_devops_hw13_builder

  roles:
    - role: builder

- name: Test Webserver
  gather_facts: false
  hosts: tag_Name_devops_hw13_webserver

  roles:
    - role: webserver
