---
- name: Create a Builder EC2 instance
  hosts: localhost
  gather_facts: false

  roles:
    - role: create_builder

- name: Test Builder
  gather_facts: false
  hosts: tag_Name_devops_hw13_builder

  roles:
    - {role: builder, builder_hostname: "{{ builder_hostname }}"}
