---
- name: Destroy the Builder EC2 instance
  hosts: localhost
  gather_facts: false

  roles:
    - role: create_builder
      tags: [down]


# - name: Test Builder
#   gather_facts: false
#   hosts: tag_Name_devops_hw13_builder
#
#   roles:
#     - builder
