---
- name: Test Builder
  gather_facts: false
  hosts: tag_Name_devops_hw13_builder

  vars:
    ansible_ssh_private_key_file: ./builder-private.key
    ansible_ssh_user: ubuntu

  tasks:
    - name: Run Shell Command
      command: uname -a
      register: test

    - name: Show Output of Shell Command
      debug:
        msg: "{{test}}"
