---
# tasks file for builder
- name: Wait for SSH to come up
  local_action:
    wait_for:
      port: 22
      state: started
      hoat: "{{inventory_hostname}}"

- name: Run Shell Command
  command: uname -a
  register: test
  tags: up

- name: Show Output of Shell Command
  debug:
    msg: "{{test}}"
  tags: up
