---
# tasks file for builder
- name: Wait for SSH to come up
  wait_for_connection:
    delay: 10
    timeout: 600
  tags: up

- name: Ensure packages are present
  apt:
    name: ['default-jre', 'maven', 'git']
    state: present
    update_cache: true
  tags: up

- name: Clone a github repository boxfuse
  git:
    repo: "{{ remote_repo }}"
    dest: "{{ repo_dir }}"
    clone: true
    update: true
  notify: "build it"
  tags: up

- name: Check the artifact exists
  stat:
    path: "{{ target_file }}"
  register: artifact_file
  changed_when: not artifact_file.stat.exists
  notify: "build it"
  tags: up

- name: Fetch webserver ssh key
  synchronize:
    src: "{{ webserver_key_filename }}"
    dest: "{{ webserver_key_filename }}"
  tags: up
