---
# tasks file for builder
- name: Wait for SSH to come up
  wait_for_connection:
    delay: 10
    timeout: 600
  tags: up

- name: Run Shell Command
  command: uname -a
  register: test
  tags: up

- name: Show Output of Shell Command
  debug:
    msg: "{{test}}"
  tags: up

- name: Import role from create_builder
  import_role:
    name: create_builder

- name: Show hostname
  debug:
    msg: "{{ builder_dns_name }}"
  tags: up
