---
# tasks file for builder
# - name: Wait for SSH to come up
#   delegate_to: localhost
#   wait_for:
#     port: 22
#     connect_timeout: 300
#     state: started

- name: Wait for SSH to come up
  wait_for_connection:
    delay: 10
    timeout: 600
  tags: up

- name: Run Shell Command
  command: uname -a
  register: test
  tags: up

- name: Show Output of Shell Command
  debug:
    msg: "{{test}}"
  tags: up
