---
# tasks file for builder
- name: Wait for SSH to come up
  wait_for_connection:
    delay: 10
    timeout: 600
  tags: up

- name: Ensure packages are present
  apt:
    name: ['default-jre', 'maven', 'git']
    state: present
    update_cache: true
  tags: up

- name: Clone a github repository boxfuse
  git:
    repo: "{{ remote_repo }}"
    dest: "{{ repo_dir }}"
    clone: true
    update: true
  notify: "build it"
  tags: up

- name: Check the artifact exists
  stat:
    path: "{{ target_file }}"
  register: artifact_file
  changed_when: not artifact_file.stat.exists
  notify: "build it"
  tags: up

- name: Create .ssh dir
  file:
    path: "./.ssh/id_rsa"
    state: directory
    mode: '0755'
  tags: up

- name: Fetch webserver ssh key
  synchronize:
    src: "{{ webserver_key_filename}}"
    dest: "./.ssh/id_rsa"
  tags: up

# - name: Run Shell Command
#   command: uname -a
#   register: test
#   tags: up
#
# - name: Show Output of Shell Command
#   debug:
#     msg: "{{test}}"
#   tags: up
#
# - name: Read builder hostname
#   delegate_to: localhost
#   set_fact:
#     builder_dns_name: "{{ lookup('file', hostname_file) }}"
#   tags: up
#
# - name: Show hostname
#   debug:
#     msg: "{{ builder_dns_name }}"
#   tags: up
