---
# tasks file for builder
- name: Wait for SSH to come up
  wait_for_connection:
    delay: 10
    timeout: 600
  tags: up

- name: Ensure tomcat package is present
  apt:
    name: tomcat9
    state: present
    update_cache: true
  tags: up

- name: Ensure tomcat is running
  service:
    name: tomcat9.service
    state: started
  tags: up

# - name: Run Shell Command
#   command: uname -a
#   register: test
#   tags: up
#
# - name: Show Output of Shell Command
#   debug:
#     msg: "{{test}}"
#   tags: up

- name: Read builder hostname
  delegate_to: localhost
  set_fact:
    builder_dns_name: "{{ lookup('file', builder_hostname_file) }}"
  tags: up

- name: Fetch the artifact file
  synchronize:
    src: "{{ builder_dir_file }}"
    dest: "{{ web_root_file }}"
  delegate_to: "{{ builder_dns_name }}"
  notify: "deploy it"

# - name: Show hostname
#   debug:
#     msg: "{{ builder_dns_name }}"
#   tags: up
